// // Create dummy user data
// import 'dart:math';
// import 'package:uuid/uuid.dart';
// import 'package:flutter/material.dart';
//
// import '../subordinate_classes/item_class.dart';
// import '../subordinate_classes/user_data.dart';
//
// UserData userData = UserData(
//   name: 'John Doe',
//   email: 'john.doe@example.com',
//   contactNumber: '+1234567890',
//   password: 'password123',
// );
//
// List<ItemData> dummyItems = [
//   // Due items
//   ItemData(
//     id: Uuid().v4(),
//     type: 'due',
//     backgroundColor: Color(0xFFA6F2D2),
//     itemName: 'Laptop',
//     completeDate: DateTime.now().subtract(Duration(days: Random().nextInt(5))),
//     status: false,
//     borrowedBy: 'John Doe',
//   ),
//   ItemData(
//     id: Uuid().v4(),
//     type: 'due',
//     backgroundColor: Color(0xFFA6F2D2),
//     itemName: 'Book',
//     completeDate: DateTime.now().subtract(Duration(days: Random().nextInt(5))),
//     status: false,
//     borrowedBy: 'Jane Smith',
//   ),
//   ItemData(
//     id: Uuid().v4(),
//     type: 'due',
//     backgroundColor: Color(0xFFA6F2D2),
//     itemName: 'Phone',
//     completeDate: DateTime.now().subtract(Duration(days: Random().nextInt(5))),
//     status: true,
//     borrowedBy: 'Alice Johnson',
//   ),
//   ItemData(
//     id: Uuid().v4(),
//     type: 'due',
//     backgroundColor: Color(0xFFA6F2D2),
//     itemName: 'Headphones',
//     completeDate: DateTime.now().subtract(Duration(days: Random().nextInt(5))),
//     status: true,
//     borrowedBy: 'Bob Williams',
//   ),
//   ItemData(
//     id: Uuid().v4(),
//     type: 'due',
//     backgroundColor: Color(0xFFA6F2D2),
//     itemName: 'Tablet',
//     completeDate: DateTime.now().subtract(Duration(days: Random().nextInt(5))),
//     status: false,
//     borrowedBy: 'Emily Davis',
//   ),
//   ItemData(
//     id: Uuid().v4(),
//     type: 'due',
//     backgroundColor: Color(0xFFA6F2D2),
//     itemName: 'Camera',
//     completeDate: DateTime.now().subtract(Duration(days: Random().nextInt(5))),
//     status: true,
//     borrowedBy: 'David Rodriguez',
//   ),
//   // ItemData(
//   //   id: Uuid().v4(),
//   //   type: 'due',
//   //   backgroundColor: Color(0xFFA6F2D2),
//   //   itemName: 'Watch',
//   //   completeDate: DateTime.now().subtract(Duration(days: Random().nextInt(5))),
//   //   status: false,
//   //   borrowedBy: 'Olivia Martinez',
//   // ),
//   // ItemData(
//   //   id: Uuid().v4(),
//   //   type: 'due',
//   //   backgroundColor: Color(0xFFA6F2D2),
//   //   itemName: 'Glasses',
//   //   completeDate: DateTime.now().subtract(Duration(days: Random().nextInt(5))),
//   //   status: true,
//   //   borrowedBy: 'Michael Brown',
//   // ),
//   // // Borrowed items
//   // ItemData(
//   //   id: Uuid().v4(),
//   //   type: 'borrowed',
//   //   backgroundColor: Color(0xFFA6F2D2),
//   //   itemName: 'Bike',
//   //   completeDate: DateTime.now().subtract(Duration(days: Random().nextInt(5))),
//   //   status: false,
//   //   borrowedBy: 'Eva Martinez',
//   // ),
//   // ItemData(
//   //   id: Uuid().v4(),
//   //   type: 'borrowed',
//   //   backgroundColor: Color(0xFFA6F2D2),
//   //   itemName: 'Guitar',
//   //   completeDate: DateTime.now().subtract(Duration(days: Random().nextInt(5))),
//   //   status: true,
//   //   borrowedBy: 'Sophia Thomas',
//   // ),
//   // ItemData(
//   //   id: Uuid().v4(),
//   //   type: 'borrowed',
//   //   backgroundColor: Color(0xFFA6F2D2),
//   //   itemName: 'Toolbox',
//   //   completeDate: DateTime.now().subtract(Duration(days: Random().nextInt(5))),
//   //   status: false,
//   //   borrowedBy: 'William Wilson',
//   // ),
//   // ItemData(
//   //   id: Uuid().v4(),
//   //   type: 'borrowed',
//   //   backgroundColor: Color(0xFFA6F2D2),
//   //   itemName: 'Drone',
//   //   completeDate: DateTime.now().subtract(Duration(days: Random().nextInt(5))),
//   //   status: true,
//   //   borrowedBy: 'Isabella Taylor',
//   // ),
//   // ItemData(
//   //   id: Uuid().v4(),
//   //   type: 'borrowed',
//   //   backgroundColor: Color(0xFFA6F2D2),
//   //   itemName: 'Keyboard',
//   //   completeDate: DateTime.now().subtract(Duration(days: Random().nextInt(5))),
//   //   status: false,
//   //   borrowedBy: 'James Anderson',
//   // ),
//   // ItemData(
//   //   id: Uuid().v4(),
//   //   type: 'borrowed',
//   //   backgroundColor: Color(0xFFA6F2D2),
//   //   itemName: 'Backpack',
//   //   completeDate: DateTime.now().subtract(Duration(days: Random().nextInt(5))),
//   //   status: true,
//   //   borrowedBy: 'Charlotte White',
//   // ),
//   // ItemData(
//   //   id: Uuid().v4(),
//   //   type: 'borrowed',
//   //   backgroundColor: Color(0xFFA6F2D2),
//   //   itemName: 'Printer',
//   //   completeDate: DateTime.now().subtract(Duration(days: Random().nextInt(5))),
//   //   status: false,
//   //   borrowedBy: 'Daniel Martinez',
//   // ),
//   // ItemData(
//   //   id: Uuid().v4(),
//   //   type: 'borrowed',
//   //   backgroundColor: Color(0xFFA6F2D2),
//   //   itemName: 'Microwave',
//   //   completeDate: DateTime.now().subtract(Duration(days: Random().nextInt(5))),
//   //   status: true,
//   //   borrowedBy: 'Amelia Jones',
//   // ),
//   // ItemData(
//   //   id: Uuid().v4(),
//   //   type: 'borrowed',
//   //   backgroundColor: Color(0xFFA6F2D2),
//   //   itemName: 'Monitor',
//   //   completeDate: DateTime.now().subtract(Duration(days: Random().nextInt(5))),
//   //   status: false,
//   //   borrowedBy: 'Benjamin Garcia',
//   // ),
//   // ItemData(
//   //   id: Uuid().v4(),
//   //   type: 'borrowed',
//   //   backgroundColor: Color(0xFFA6F2D2),
//   //   itemName: 'Projector',
//   //   completeDate: DateTime.now().subtract(Duration(days: Random().nextInt(5))),
//   //   status: true,
//   //   borrowedBy: 'Mia Johnson',
//   // ),
// ];
